name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-11-jdk \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev \
          build-essential ccache \
          libltdl-dev libffi-dev libssl-dev python3-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install --upgrade cython==0.29.36
        pip install --upgrade buildozer
        pip install --upgrade git+https://github.com/kivy/python-for-android.git@develop
        
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
        
    - name: Build APK
      run: |
        yes | buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: universal-soul-ai-apk
        path: bin/*.apk
        retention-days: 90
